baseURL = "http://3c273.fr"
languageCode = "fr-FR"
title = "3C 273 - notes d'observations, dessins et photographies du ciel"
paginate=20
[taxonomies]
  category="categories"
  tag="tags"
  catalog="catalogs"
  designation="designations"
  constellation="constellations"